import NextTopLoader from "nextjs-toploader";
import MainProvider from "./Context/MainContext";
import "./globals.css";
import { Suspense } from "react";

export const metadata = {
  title: "Xem Tua",
  description: "Generated by Miwabox",
};

function importAll(r) {
  r.keys().forEach(r);
}

importAll(require.context('./css', false, /\.css$/));


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MainProvider>
      <body>
        <NextTopLoader
          showSpinner={false}
          zIndex={1600}
          color="blue"
          speed={999}
        />
        <Suspense>
        <main>{children}</main>
        </Suspense>
      </body>
      </MainProvider>
    </html>
  );
}
